version: "3"
services: 
    db:
        image: mariadb
        command: --max-allowed-packet=64MB
        restart: always
        # networks: 
        #     - default
        volumes: 
            - db_vol:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
        # env_file: 
        #     - ./conf/db.env
    app:
        image: matomo:fpm-alpine
        restart: always
        depends_on: 
            - db
        # networks: 
        #     - default
        volumes: 
            - ./matomo:/var/www/html
        environment: 
            MATOMO_DATABASE_HOST: db
            MATOMO_DATABASE_ADAPTER: "${MATOMO_DATABASE_ADAPTER}"
            MATOMO_DATABASE_TABLES_PREFIX: "${MATOMO_DATABASE_TABLES_PREFIX}"
            MATOMO_DATABASE_USERNAME: "${MYSQL_USER}"
            MATOMO_DATABASE_PASSWORD: "${MYSQL_PASSWORD}"
            MATOMO_DATABASE_DBNAME: "${MYSQL_DATABASE}"
        # env_file: 
        #     - ./conf/db.env
    web:
        image: nginx:alpine
        restart: always
        depends_on: 
            - app
        volumes: 
            - ./matomo:/var/www/html:ro
            - ./conf/nginx/matomo.conf:/etc/nginx/conf.d/default.conf:ro
        networks: 
            - default
            - traefik
        # ports:
        #     - 8080:80
        labels: 
            - "traefik.enable=true"
            # Service
            - "traefik.http.services.matomo.loadbalancer.server.port=80"
            # Http
            - "traefik.http.routers.matomo_http.entrypoints=web"
            - "traefik.http.routers.matomo_http.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.matomo_http.service=matomo"
            # https
            - "traefik.http.routers.matomo_https.entrypoints=web_secure"
            - "traefik.http.routers.matomo_https.tls=true"
            - "traefik.http.routers.matomo_https.tls.options=intermediate@file"
            - "traefik.http.routers.matomo_https.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.matomo_https.service=matomo"
            # - "traefik.http.routers.matomo_https.middlewares=hsts-header@file"
            
volumes: 
    db_vol:
networks: 
    traefik:
        external: 
            name: frontend
